### PR TITLE
test: test `fail`-argument

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Comment by YDX-2147483647** [comment]
The cause of this issue is trivial: `$INPUT_FAIL` gets changed to `true` because of `failIfEmpty: true`, which is the default. The line `INPUT_FAIL=true` was introduced in #86.

https://github.com/lycheeverse/lychee-action/blob/ae4699150ab670dcfb64cc74e8680e776d9caae2/entrypoint.sh#L34-L39
https://github.com/lycheeverse/lychee-action/blob/ae4699150ab670dcfb64cc74e8680e776d9caae2/action.yml#L17-L19

To verify it, I set `failIfEmpty: false` to the step in `test.yml`, and now it does pass.

```diff
  - name: test disable fail - it's okay if we fail
    uses: ./
    with:
      args: --no-progress foo.bar
      fail: false
+     failIfEmpty: false
```

<small>Thanks https://github.com/nektos/act for making it _a lot_ easier to debug.</small>

## Possible fix

Document this behaviour, or edit `entrypoint.sh`:

```diff
	# Overwrite the exit code in case no links were found
	# and `failIfEmpty` is set to `true` (and it is by default)
	if [ "${INPUT_FAILIFEMPTY}" = "true" ]; then
-	    # Explicitly set INPUT_FAIL to true to ensure the script fails
-	    # if no links are found
-	    INPUT_FAIL=true
	    # This is a somewhat crude way to check the Markdown output of lychee
	    if grep -E 'Total\s+\|\s+0' "${LYCHEE_TMP}"; then
	        echo "No links were found. This usually indicates a configuration error." >> "${LYCHEE_TMP}"
	        echo "If this was expected, set 'failIfEmpty: false' in the args." >> "${LYCHEE_TMP}"
	        exit_code=1
+	        # Explicitly set INPUT_FAIL to true to ensure the script fails
+	        # if no links are found
+	        INPUT_FAIL=true
	    fi
	fi
```

I can make a PR if wanted.

**Comment by mre** [comment]
Thanks for the investigation. I'm all for changing the code here. The way I see it,

- If `fail: false` and `failIfEmpty` is not set, don't fail if the status code is not 0 but fail if links were found.
- If `fail` is not set, and `failIfEmpty: false`, fail if the status code is not 0 but don't fail if there are no links. 
- If none is set, use the defaults: fail if the status code is not 0 or no links were found. 

Please correct me if I'm wrong.

I'd appreciate a pull request.

**Comment by YDX-2147483647** [comment]
Maybe this PR can be merged first?
If #262 needs more tests, but this PR is not merged, then there will be a merge conflict later.

**Comment by mre** [comment]
> Maybe this PR can be merged first?

Do you mean *this* PR? (251)

Because it currently fails.
I checked out your PR (https://github.com/lycheeverse/lychee-action/pull/262) and that passes and seems to fix the issue, no? I think we can close this one (251) and merge yours. Or am I missing something?

**Comment by mre** [comment]
Ah, I think I understand now. Can you merge the changes of this PR into your branch? Then we have all changes (including a passing test) in one pull request. I prefer that, because it's a single atomic change and we can make sure it works. I'd rather not merge a change if the pipeline is red. 😉

**Comment by mre** [comment]
@sebastiaanspeck, this PR got merged as part of #262 by @YDX-2147483647.
Good work by both of you. 🎉

**Pull request closed without merging**
