### PR TITLE
Add `*.rst` glob pattern to defaults

### PR DESCRIPTION
**Pull request by kdeldycke**
Lychee is advertising its capability of checking reStructuredText files, so I guess it is a good idea to add these files to the default glob pattern.

### CODE REVIEW

**Comment by mre** [comment]
Hey Kevin, great idea!

Code looks good.
Could you also add an example `fixtures/TEST.rst` file with some links and add a test like [this](https://github.com/lycheeverse/lychee-action/blob/21b2b78c236322f7dcf5b8dbddaa6442f39c2f32/.github/workflows/test.yml#L35-L41)? (Ideally, we'd want to check the links it found in the tests as well, but at the moment we only test the lychee invocation.)

**Comment by kdeldycke** [comment]
> Could you also add an example `fixtures/TEST.rst` file with some links and add a test like [this](https://github.com/lycheeverse/lychee-action/blob/21b2b78c236322f7dcf5b8dbddaa6442f39c2f32/.github/workflows/test.yml#L35-L41)? (Ideally, we'd want to check the links it found in the tests as well, but at the moment we only test the lychee invocation.)

Done!

Is that good to you? Can you approve the workflow run on that PR so we can check everything's fine?

**Comment by mre** [comment]
You got it.

**Comment by kdeldycke** [comment]
Thanks @mre for the fast merge and feedback!

**Pull request merged**
