### PR TITLE
Update README.md with method for failing the action

### PR DESCRIPTION
**Pull request by Stargator**
@mre Here is the update. I am not sure about the wording, but the config syntax is correct.

### CODE REVIEW

**Comment by Stargator** [comment]
@mre wow, that was FAST! :)

**Comment by mre** [comment]
Thanks for the contribution. The text sounds good.

**Comment by mre** [comment]
Yeah I happened to see it on the phone thanks to GitHub's new push notifications on the mobile app.

**Comment by Stargator** [comment]
Just for your awareness, the id `checker` is what is referenced in the exit logic, so the Link check job would need an `id` defined. That is what makes it work.

**Comment by mre** [comment]
Good point. I'll rename that to lychee because it's closer to the action name.

**Pull request merged**
